---
title: "REAMDE"
output: html_document
---
#REAMDE
The **run-analysis.R** scripts ingest untidy  raw data and cleans up the 
data premised on data tidy rules. ie -observations are in rows - variables are in
columns - contained in a single dataset, and saves it as csv file.  

The script first downloads a human activity recognition raw dataset collected from 
smartphone (samsung-II) with its embedded accelerometer and gyroscope.
The raw dataset can be downloaded [from here](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip). 

The script will then unzip and load the following files in R  working directory. 
```
activity_labels  #Links the class labels with their activity name
features         #List of all features

subject_test     #volunteers 1 - 30
y_test           #activity 1-6
X_test           #Test dataset

subject_train    #volunteers 1- 30
y_train          #Activity 1 -6
X_train          #Test data set
```

The user can run the **_run-analysis.R_** script from the R or R sutdio IDE - which will generate a data.table 
named **ActvRecgnData.csv** saved in a hard drive. From there, the file is ready 
to be used for anlysis and inference.  The .csv file can be opned by any editor/tool that can read csv format. 

The following versions for integrated development environment (IDE)  and the packages were  installed prior to running the sciprt.
    

    IDE      R studio      3.2.0
    package  data.table    1.9.4 
    package  dplyr         0.4.2      
    package  plyr          1.8.3 
    
Take a look at the **CodeBook** marked document for information on the layout of the data set, the variables
and their definitions, any units of measurement.




-----------------**_End of README File_**---------------
